---
- name: Install Apache Server
  hosts: node2
  become: yes
  tasks:
    - name: Update package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Copy HTML file
      copy:
        src: index.html
        dest: /var/www/html/index.html
